export default {
    navbarItems: [
      {
        name: "Home",
        route: "home",
        type: "menu",
        tooltip: "View Company Relations",
        requiredPermissions: ["READ_RELATIONS"],
        items: [
          {
            name: "Customers",
            tooltip: "customers",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Vendors",
            tooltip: "vendors",
            route: "vendors",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Bank Accounts",
            tooltip: "bank accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Chart nf Accounts",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          }
        ]
      },
      {
        name: "Finance",
        route: "home",
        type: "menu",
        tooltip: "View Company Relations",
        requiredPermissions: ["READ_RELATIONS"],
        items: [
          {
            name: "General Journals",
            tooltip: "customers",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Chart of Account",
            tooltip: "vendors",
            route: "vendors",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "G/L Account Categories",
            tooltip: "bank accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "GL Budget",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "fixed Assets",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Financial Reporting",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Instant Journals",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Sales Budget",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Purchase Budget",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Sales Analysis Reports",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Pruchase Analysis Report",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Inventory Analysis Report",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Vat Return",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Currencies",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Employees",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "VAT Statements",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Dimensions",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Statical Accounts",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Posted General Journals",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Instant Reports",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          }
        ]
      },
      {
        name: "Cash Managements",
        route: "home",
        type: "menu",
        tooltip: "View Company Relations",
        requiredPermissions: ["READ_RELATIONS"],
        items: [
          {
            name: "Cash Flow Forecasts",
            tooltip: "customers",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Chart of cash flow Accounts",
            tooltip: "vendors",
            route: "vendors",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Cash flow Manual Revenues",
            tooltip: "bank accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Cash Flow Manual Expenses",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Cash Receipt Journals",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Payment Journals",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Bank Accounts",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Bank Account Statement",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Payment Recc Journals",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Direct Debit Collections",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Payment Terms",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Bank Deposit",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Bank Account Reconciliations",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          }
        ]
      },
      {
        name: "Company Relations",
        route: "companyRelations",
        type: "link",
        tooltip: "View Company Relations",
        requiredPermissions: ["READ_RELATIONS"],
      },
      {
        name: "Sales",
        route: "home",
        type: "menu",
        tooltip: "View Company Relations",
        requiredPermissions: ["READ_RELATIONS"],
        items: [
          {
            name: "Customers",
            tooltip: "customers",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Items",
            tooltip: "vendors",
            route: "vendors",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Sales Quotes",
            tooltip: "bank accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Sales Ordders",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Blanket Sales Order",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Sales Invoices",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Sales Credit Memos",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Sales Return Order",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Reminders",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Finance Charge Memos",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Posted Sales Invoices",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Posted Sales Credit Memos",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Posted Sales Return Receipts",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Posted Sales Shipments",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Issued Reminders",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Issued Finance Charge Memos",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          }
        ]
      },
      {
        name: "Purchasing",
        route: "home",
        type: "menu",
        tooltip: "View Company Relations",
        requiredPermissions: ["READ_RELATIONS"],
        items: [
          {
            name: "Vendors",
            tooltip: "customers",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Incoming Documents",
            tooltip: "vendors",
            route: "vendors",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Item Charges",
            tooltip: "bank accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Purchase Quotes",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Purchase Order",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Blanket Purchase Order",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Purchase Invoice",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Purchase Credit Memos",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Purchase Return Order",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Posted Purchase Invoice",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Posted Purchase Credit Memos",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Posted Purchase Reciepts",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Posted Purchase Return Shipements",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          }
        ]
      },
      {
        name: "Shopify",
        route: "home",
        type: "menu",
        tooltip: "View Company Relations",
        requiredPermissions: ["READ_RELATIONS"],
        items: [
          {
            name: "Shops",
            tooltip: "customers",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Customers",
            tooltip: "vendors",
            route: "vendors",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Products",
            tooltip: "bank accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Orders",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Refunds",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Returns",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Gift Cards",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Transactions",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          },
          {
            name: "Payouts",
            tooltip: "chart nf accounts",
            route: "customers",
            type: "link",
            requiredPermissions: ["READ_DOCUMENTATION"],
          }    
        ]
      }
    ],
    administratorModule: 
      {
        icon: "bi-wrench",
        tooltip: "Administrator module",
        type: "dropdown",
        requiredPermissions: ["READ_ADMINISTRATOR"],
        items: [
          {
            name: "User in app",
            tooltip: "Edit users in app",
            route: "admin/users",
            type: "link",
            requiredPermissions: ["EDIT_ADMIN"],
          },
        ],
      },
    userToolbar: 
      {
        name: "NAME_OF_THE_USER",
        tooltip: "View settings",
        type: "dropdown",
        requiredPermissions: ["READ_USER"],
        items: [
          {
            name: "Settings",
            tooltip: "Edit settings",
            route: "user/settings",
            type: "link",
            requiredPermissions: ["EDIT_USER"],
          },
        ],
      },
    
  };
  